apiVersion: "1"

services:
  - type: web
    name: wp-app
    env: docker
    dockerfilePath: Dockerfile
    plan: starter
    envVars:
      - key: DB_NAME
        value: wp
      - key: DB_USER
        value: wp
      - key: DB_PASSWORD
        fromService:
          type: private_service
          name: db
          envVarKey: MYSQL_PASSWORD
      - key: DB_HOST
        value: db:3306
      - key: WP_HOME
        value: https://wp-csv-import-assignment.onrender.com
      - key: WP_SITEURL
        value: https://wp-csv-import-assignment.onrender.com
      - key: CPI_JWT_SECRET
        generateValue: true
    disk:
      name: wp-uploads
      mountPath: /var/www/html/wp-content/uploads
      sizeGB: 2

privateServices:
  - type: private_service
    name: db
    env: docker
    dockerfilePath: mysql.Dockerfile
    plan: starter
    envVars:
      - key: MYSQL_DATABASE
        value: wp
      - key: MYSQL_USER
        value: wp
      - key: MYSQL_PASSWORD
        generateValue: true
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 2